name: website

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
      - docs
    # Alternative: only build for tags.
    # tags:
    #   - '*'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create config file
        run: |
          cat << EOF > config.py
          tokens = {
          'discord_token': ${{ secrets.DISCORD_TOKEN }},
          'finnhub_token': ${{ secrets.FINNHUB_TOKEN }}
          }
          EOF
      # We use a custom build script for pdoc itself, ideally you just run `pdoc -o docs/ ...` here.
      - run: PYTHONPATH=src pdoc -o docs --html --force src
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
